-- CIS report tile: Bags Movement (traceability.bags_movement).
-- Permission is defined in app/permissions.py. Assign per user in CIS → Users & access.
-- Intentionally no auto-grant here — existing user_permissions rows are never removed.